### ISSUE TITLE
[API] Initializers for `value`-holding types

### ISSUE THREAD

**Issue by jsbean** [dn-m/MusicXML#103]
There are many types which have properties named `value`, which are generally "Simple Types", and are what `XMLCoder` calls "Coding Key Value Intrinsic". In XML parlance, complex types "extend" "Simple Types" with attributes.

For these types, we can remove the attribute label in initializers, as these types are required and usually self-explanatory.

For example, the complex type [`stem`](https://usermanuals.musicxml.com/MusicXML/Content/CT-MusicXML-stem.htm) "extends" the [`stem-value`](https://usermanuals.musicxml.com/MusicXML/Content/ST-MusicXML-stem-value.htm) type.

I suggest we implement initializers for types like this:

```Swift
extension Stem {
    init(_ value: StemValue, ...) {
        self.value = value
        ...
    }
}
```

Which make the call site look something like this:

```Swift
let stem = Stem(.up)
```

@DJBen, does this work for or against any of your thoughts on the matter?

**Comment by DJBen** [comment]
I think this makes sense and I agree. We just want to make sure this case applies to simple types only.

**Comment by jsbean** [comment]
I think this methodology could also be extended to types which are inherently attributed arrays of a union type (i.e., `Kind`) (e.g., `Notations`, `Ornaments`, `Dynamics`, `Technical`, `Encoding`, etc.).

Thus, we could have:

```Swift
let notations = Notations([.ornaments(Ornaments([.mordent(Mordent())]))])
```

Instead of:

```Swift
let notations = Notations(
    values: [
        .ornaments(
            Ornaments(
                values: [
                    .mordent(Mordent())
                ]
            )
        )
    ]
)
```

Furthermore, we _could_ make these types conform to `ArrayLiteralConvertible` if they are simple cases like so (without attributes).

```Swift
let notations = Notations([.ornaments([.mordent(Mordent()))])
```

**Comment by jsbean** [comment]
And to really stretch the ergonomics, we _may_ be able to get away with defining static properties on top of these union types:

```Swift
extension Ornament {
    static let mordent = Ornament.mordent(Mordent())
}
```

Thus making the previous example:

```Swift
let notations = Notations([.ornaments([.mordent])])
```

Not entirely certain that the compiler will appreciate this, but it could be worth a try.

**Comment by DJBen** [comment]
> And to really stretch the ergonomics, we _may_ be able to get away with defining static properties on top of these union types:
> 
> ```swift
> extension Ornament {
>     static let mordent = Ornament.mordent(Mordent())
> }
> ```
> 
> Thus making the previous example:
> 
> ```swift
> let notations = Notations([.ornaments([.mordent])])
> ```
> 
> Not entirely certain that the compiler will appreciate this, but it could be worth a try.

We can already specify default values to the `enums`, like

```swift
enum Ornament {
    case mordent(Mordent = Mordent())
}
```

**Comment by jsbean** [comment]
Wait, whoa, what?! When did that happen? I'm gonna give that a shot.

**Comment by jsbean** [comment]
That's wild. The only slightly noisy aspect is that it has to be called as `.mordent()` rather than `.mordent`, but that is very interesting.
