### ISSUE TITLE
Audit placement of Header

### ISSUE THREAD

**Issue by jsbean** [dn-m/MusicXML#169]
Currently both `Timewise` and `Partwise` have a property `header: Header`. Isn't this better suited at the `Score` level?

**Comment by DJBen** [comment]
header's content - "work", "movement-number" etc are under both `score-partwise` and `score-timewise` definition. IMO they should exist in both of the score traversal data models.

Speaking of `Score` model, I found it behaving like a wrapper around `Traversal` and adds no additional information. Could we get rid of one layer by killing the current `Score` model, and renaming `Traversal` to be the new `Score`? What do you think?

**Comment by jsbean** [comment]
> header's content - "work", "movement-number" etc are under both `score-partwise` and `score-timewise` definition. IMO they should exist in both of the score traversal data models.

Works for me!

> Speaking of `Score` model, I found it behaving like a wrapper around `Traversal` and adds no additional information. Could we get rid of one layer by killing the current `Score` model, and renaming `Traversal` to be the new `Score`? What do you think?

I agree there there is an extra level here. That being said `Score` actually has a property (`version`) that is not yet implemented. I think `Score` should continue to exist as it is, as should `Traversal`. However, I think that `MusicXML` should not be the value of focus. We should remove the `MusicXML` and pass around the `Score` as the thing being decoded / encoded.

**Comment by jsbean** [comment]
Actually, let me step back. Let's put `version` in `Header` and do what you say: rename `Traversal` to `Score.

**Comment by jsbean** [comment]
I am going to close this and continue this conversation in #166.
