### ISSUE TITLE
"Je fais un rêve"

### ISSUE THREAD

**Issue by jsbean** [dn-m/MusicXML#175]
The `Après un rêve` test sample is not decoding properly. Let's smoke it out.

**Comment by jsbean** [comment]
Ahh, is it just this: https://github.com/MaxDesiatov/XMLCoder/pull/142 ?

**Comment by DJBen** [comment]
No it's more than that - this will only break the comparison but doesn't break parsing.

**Comment by jsbean** [comment]
Ahh, good to know!

**Comment by DJBen** [comment]
Can we close it? Looks like you fixed it. Kudos!
