### ISSUE TITLE
Decide top level element using regex match against <!DOCTYPE (score-partwise|score-timewise) 

### ISSUE THREAD

**Issue by DJBen** [dn-m/MusicXML#182]
Currently we have no way to know the top element to be whether `score-partwise` or `score-timewise`. We work around by attempting `score-partwise` decoder first and upon catching any error, falling back to `score-timewise`.

This sweeps potential decoding issues under the rug. For example, if our decoder has a bug when decoding partwise score, it will be caught by this logic and attempting to use `score-timewise` to decode it and fails unsurprisingly, completely swallowing any errors and making our debugging process difficult.

I inquired in XMLCoder for ways to decode `<!DOCTYPE>`, and get negative answers. I am thinking to use a simple regex matcher to extract top-level tag name. It should be robust enough given all music xml DTD declarations are fairly consistent.

What do you think? Looking forward to your opinions.

**Comment by jsbean** [comment]
Yes, the current implementation is unfortunate. I would give this a try, and we should throw a bunch of real-world scores at it.

**Comment by DJBen** [comment]
I investigated a bit this weekend, and found that I couldn't address this in `MusicXML` repo, because all decodings happen in the `Codable` protocol implementations where we only have access to the decoder and container but not the raw xml data.

**Comment by jsbean** [comment]
At the `Score` level, which I assume will be the most common interface, could you do something in the `Score.init(string:)`? You could run the regex there and dispatch accordingly?

We could also forward the `URL` initializer to the `String` initializer instead of jumping directly to the `Data` initializer?

**Comment by DJBen** [comment]
I think the `init(string:)` does not belong to the `Score` layer. In the future we want our custom `MusicXMLDecoder` (#179) to decoder the xml, and it will look like 

```swift
try MusicXMLDecoder().decode(Score.self, from: data)
```

In `Score` all the decoding will be constrained in the Codable protocol implementations, and `Score` does not have the raw access to the string.

Instead, we might be able to adopt the regex detection in `MusicXMLDecoder` that writes a [`userInfo`](https://developer.apple.com/documentation/swift/decoder/2892930-userinfo) to to the `decoder` to indicate the top level element type for `Score` to determine which traversal it takes.

What do you think?

**Comment by jsbean** [comment]
> I think the `init(string:)` does not belong to the `Score` layer. In the future we want our custom `MusicXMLDecoder` (#179) to decoder the xml, and it will look like
>
> ```swift
> try MusicXMLDecoder().decode(Score.self, from: data)
> ```

Ahh, I think this is a valid position.
 
> In `Score` all the decoding will be constrained in the Codable protocol implementations, and `Score` does not have the raw access to the string.
> 
> Instead, we might be able to adopt the regex detection in `MusicXMLDecoder` that writes a [`userInfo`](https://developer.apple.com/documentation/swift/decoder/2892930-userinfo) to to the `decoder` to indicate the top level element type for `Score` to determine which traversal it takes.
> 
> What do you think?

That sounds very compelling. I don't totally have my head around it yet. Could you put together a prototype?

One note: the `MusicXMLDecoder` project is a bit held back by the copyright character whitespace parsing issue (round trips with the `(Music)XMLEncoder` using `.prettyPrinted` are not equivalent when decoded with whitespace trimming disabled on the `MusicXMLDecoder`).

**Comment by jsbean** [comment]
Closed by #202. Thanks, @DJBen!
