### ISSUE TITLE
Problems importing with Xcode 11.1 Swift Package

### ISSUE THREAD

**Issue by yangyangnote** [dn-m/MusicXML#183]
When I try to import with Swift Package in Xcode 11.1, I get an error.

> Showing All Messages : the package musicxml[https://github.com/dn-m/MusicXML.git] @ 0.2.0 contains incompatible dependencies: xmlcoder[https://github.com/jsbean/XMLCoder] @ master 

![截屏2019-10-18下午4 37 34](https://user-images.githubusercontent.com/19338570/67079502-e6877880-f1c5-11e9-912d-47aabf430639.png)

Is there a solution?Thank you !

**Comment by jsbean** [comment]
Thanks for reporting this, @yangyangnote! I will look into this right away.

**Comment by jsbean** [comment]
I have reproduced this, and will continue to investigate.

**Comment by jsbean** [comment]
For now, try adding `MusicXML` from `branch` `latest`. That works on my end.

**Comment by DJBen** [comment]
Was able to repro the issue. +1 if you use `branch: latest` you should be fine.
@jsbean we might want to republish version 0.2.0.

To not repeat the same issue, I think we should use a SHA instead of a branch in dependency https://github.com/dn-m/MusicXML/blob/0.2.0/Package.swift

**Comment by jsbean** [comment]
@DJBen, thanks for giving this a look. I agree about republishing `0.2.0` with a SHA and continuing to do so in perpetuity.

**Comment by jsbean** [comment]
I have published `0.2.1` which addresses this problem. @yangyangnote, let me know if this works for you!

**Comment by yangyangnote** [comment]
@jsbean  When I choose version 0.21, the same error will be reported.Is there something wrong with my import method？


![截屏2019-10-23下午4 06 26](https://user-images.githubusercontent.com/19338570/67371702-61c6a100-f5af-11e9-9399-e1863c1536fa.png)

**Comment by jsbean** [comment]
What the. I will check this out. Thanks for your patience!

**Comment by jsbean** [comment]
Hi @yangyangnote, I've created #191. Try using the `MusicXML` @ `branch` `xmlcoder-version` if you want to try it out before it gets merged in.

Then I will release this as `0.2.2`.

**Comment by jsbean** [comment]
@yangyangnote, give `0.2.2` a go.

**Comment by yangyangnote** [comment]
@jsbean  I finally succeeded, thank you for your help.🎉🎉🎉
