### ISSUE TITLE
How to play music from MusicXML

### ISSUE THREAD

**Issue by MarcSky** [dn-m/MusicXML#23]
Can you help me please. I write a music editor. Please tell me whether it is realistic to play music from this format in Audio Toolbox iOS? And how can I do this? Thank you.

**Comment by jsbean** [comment]
Apologies for the delayed response. 

This project may or may not be mature enough to contribute to a solution for you, as it is still a work-in-progress.

In time, this will be useful for converting MusicXML-formatted representations of scores into the Swift language. This package will not produce audio, nor will it even produce a score model entirely prepared to drive an audio engine. With this package, one will have the raw model in place which can be transformed into a data structure suitable for feeding an audio generating framework. 

I would suggest looking into [AudioKit](https://github.com/AudioKit/AudioKit), and particularly the [AKAppleSequencer](https://github.com/AudioKit/AudioKit/blob/master/AudioKit/Common/Sequencing/Apple%20Sequencer/AKAppleSequencer.swift) for the playback mechanism.

I can imagine a pipeline looking something like this:

`YourScore.xml` -> `MusicXML` -> Your custom transformations -> `AKAppleSequencer` -> 🔈
