### ISSUE TITLE
Implement Ties struct

### ISSUE THREAD

**Issue by jsbean** [dn-m/MusicXML#42]
A `Normal` note may have `0`, `1`, or `2` `<tie>` elements.

We should represent this as a struct with two optional fields: 

```Swift
struct Ties {
    let start: Tie?
    let stop: Tie?
}
```

and add a `ties` property to `Note.Normal`.

**Comment by DJBen** [comment]
Can we close this?

**Comment by jsbean** [comment]
Sure thing!
